### ISSUE TITLE
Add "or" logic to the filters.

### ISSUE THREAD

**Issue by 1rosehip** [1rosehip/jplist-es6#10]

**Comment by 1rosehip** [comment]
Added support in v1.1.1

**Comment by marcel-mpunkt** [comment]
if sorting and or-logic is applied at the same time, e.g. male and female items in alphabetical order :
first males are sorted, then females are sorted alphabetically, instead of both together.
for example: 
adam  -> peter -> zac -> alaya -> berta -> julie 
instead of:
adam -> alaya -> berta -> julie -> peter -> zac
